---

- name: "Handle admin user"
  hosts: localhost
  become: true
  vars:
    admin_password: "Ansibl3!zzZ"
    admin_hash:     "{{ admin_password|password_hash }}"
  tasks:
    - name: "Read previous hash"
      getent:
        database: "shadow"
        key: "admin"
        fail_key: false
    - name: "Set hash password to old value"
      set_fact:
        admin_hash: "{{ ansible_facts.getent_shadow.admin[0] }}"
      when: >
        ansible_facts.getent_shadow.admin.0 is defined and
        admin_password|checkpw(ansible_facts.getent_shadow.admin.0)
    - name: "Handle admin user"
      user:
        name:     "admin"
        password: "{{ admin_hash }}"
