---

- name: "Install Grafana"
  hosts: all
  gather_facts: false
  tasks:

    - name: "Install Grafana and nssm"
      chocolatey.chocolatey.win_chocolatey:
        name: ["grafana", "nssm"]
        state: present

    - name: "Configure firewall for grafana"
      community.windows.win_firewall_rule:
        name:      "Grafana server"
        localport: "3000"
        action:    allow
        direction: in
        protocol:  tcp
        state:     present
        enabled:   yes

    - block:
        - name: "Start grafana"
          # Store service definition in a YAML variable
          ansible.windows.win_service: &start-grafana-service
            name: "grafana-server"
            description: "Grafana server"
            dependencies: [ "Tcpip" ]
            state: started
            start_mode: auto

      rescue:
        - name: "Find grafana"
          ansible.windows.win_find:
            patterns: 'grafana.exe'
            paths: 'C:\ProgramData\chocolatey\lib\grafana'
            recurse: true
          register: _

        - name: "Create service for Grafana"
          community.windows.win_nssm:
            name:        "grafana-server"
            application: '{{ _.files[0].path }}'
            arguments: 'server'

        - name: "Start grafana"
          # Retrieve service definition from YAML variable
          ansible.windows.win_service: *start-grafana-service
