---

- name: "Install Prometheus"
  hosts: all
  gather_facts: false
  tasks:
    - name: "Install Prometheus"
      chocolatey.chocolatey.win_chocolatey:
        name: "prometheus"
        state: present

    - name: "Configure firewall for prometheus"
      community.windows.win_firewall_rule:
        name:      "Prometheus server"
        localport: "9090"
        action:    allow
        direction: in
        protocol:  tcp
        state:     present
        enabled:   yes

    - name: "Activate Prometheus"
      ansible.windows.win_service:
        name: "prometheus-service"
        state: started
        start_mode: auto
