---

- name: "apache installation"
  dnf:
    name: "httpd"
    state: "present"

- name: "apache service activation"
  ansible.builtin.service:
    name: "httpd"
    state: "started"
    enabled: true

- name: "Allow http connections"
  ansible.posix.firewalld:
    service: "http"
    permanent: true
    state: enabled
