---

- name: "Playbook speed test"
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Create a bunch of directory"
      ansible.builtin.file:
        path: /tmp/test/{{ item }}
        state: directory
      loop: "{{ range(50) | list }}"
