---

- name: "mariadb-server installation"
  ansible.builtin.dnf:
    name:  "mariadb-server,python3-PyMySQL"
    state: "installed"

- name: "start mariadb service"
  ansible.builtin.service:
    name:  "mariadb"
    state: "started"
    enabled: true

- name: "Allow mariadb connections"
  ansible.posix.firewalld:
    service: "mysql"
    permanent: true
    state: enabled

- name: "Listen on all interfaces"
  ansible.builtin.lineinfile:
    path: "/etc/my.cnf.d/mariadb-server.cnf"
    line: "bind-address=*"
    insertafter: "[galera]"
    regexp: "bind-address"
  notify: ["mariadb restart"]
