---
- name: Destroy
  hosts: all
  connection: local
  gather_facts: false
  vars:
    network_name: test-network
  # no_log: "{{ molecule_no_log }}"
  collections: [ "containers.podman" ]
  tasks:
    - name: "Delete Apache containers"
      podman_container:
        name:      "{{ inventory_hostname }}"
        state:     absent
    - name: "Delete podman network"
      run_once: true
      podman_network:
        name: "{{ network_name }}"
        state: absent
