---

- name: "MediaWiki db configuration"
  hosts: apache
  gather_facts: true
  gather_subset: "network"
  tags: [ "mariadb", "mysql" ]
  roles:
    - role: "mediawiki/mariadb"
      delegate_to: "{{ groups.mysql.0 }}"

- name: "MediaWiki apache configuration"
  hosts: apache
  tags: "apache"
  gather_facts: false
  roles:
    - role: "mediawiki/configuration"
