---

- name: "Apache installation"
  hosts: apache
  tasks:
    - name: "Apache package installation"
      ansible.builtin.yum:
        name: "httpd"
        state: "present"
    - name: "Apache configuration"
      ansible.builtin.template:
        src: "inventory.conf.j2"
        dest: "/etc/httpd/conf.d/inventory.conf"
        owner: "apache"
        group: "apache"
    - name: "Allow http connections"
      ansible.posix.firewalld:
        service: "http"
        permanent: yes
        state: enabled
    - name: "Start apache service"
      ansible.builtin.service:
        name: "httpd"
        state: "restarted"
        enabled: yes
      tags: [ "restart" ]
