---

- name: "Apache installation"
  hosts: inventory
  tasks:
    - name: "Apache package installation"
      ansible.builtin.yum:
        name: "httpd"
        state: "present"
    - name: "Apache configuration"
      ansible.builtin.template:
        src: "inventory.conf.j2"
        dest: "/etc/httpd/conf.d/inventory.conf"
        owner: "apache"
        group: "apache"
      # register execution result for template creation
      register: apache_conf
    # debug instruction to get apache_conf content
    - ansible.builtin.debug: var=apache_conf
    - name: "Allow http connections"
      ansible.posix.firewalld:
        service: "http"
        permanent: true
        state: enabled
    - name: "Restart apache service"
      ansible.builtin.service:
        name: "httpd"
        state: "restarted"
      # restart if necessary
      when: apache_conf is changed
    - name: "Start apache service"
      ansible.builtin.service:
        name: "httpd"
        state: "started"
        enabled: true
