---

- name: "apache installation"
  ansible.builtin.dnf:
    name: "httpd"
    state: "present"

- include_tasks: "php-install.yml"
  # force boolean evaluation
  when: php_install|bool

- name: "apache service activation"
  ansible.builtin.service:
    name: "httpd"
    state: "started"
    enabled: true

- name: "Allow http connections"
  ansible.posix.firewalld:
    service: "http"
    permanent: true
    state: enabled
