---

- name: "epel activation"
  ansible.builtin.dnf:
    name: "epel-release,epel-next-release"
    enablerepo: powertools

- name: "remi repo activation"
  ansible.builtin.dnf:
    name: "https://rpms.remirepo.net/enterprise/remi-release-8.rpm"
    state: present
    disable_gpg_check: true

- name: "Import GPG Key"
  rpm_key:
    state: present
    key: "/etc/pki/rpm-gpg/{{ item }}"
  loop: ["RPM-GPG-KEY-remi", "RPM-GPG-KEY-remi2020", "RPM-GPG-KEY-remi2021", "RPM-GPG-KEY-remi2022"]

- name: "install php82 packages"
  ansible.builtin.dnf:
    name: "php85-php,php85-php-mysqlnd,php85-php-xml,php85-php-mbstring,php85-php-gd,php85-php-intl"
    state: present
    enablerepo: "remi-8.5"
  changed_when: true
  # We need to restart apache
  notify: [ "apache restart" ]
